INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Emrullah','Kocmar');
INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Anders','Hendeus');
INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Oscar','Soler');
INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Caroline','Sandqvist');
