INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Emrullah','Kocmar');
INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Anders','Hendeus');
INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Oscar','Soler');
INSERT INTO PLAYER_TBL (PLAYER_NAME,PLAYER_SURNAME) VALUES ('Caroline','Sandqvist');

INSERT INTO GAME_TBL (GAME_NAME,GAME_GENRE,GAME_MANUFACTURER) VALUES ('Poker','Casino','ComeOn');
INSERT INTO GAME_TBL (GAME_NAME,GAME_GENRE,GAME_MANUFACTURER) VALUES ('Blackjack','Casino','ComeOn');
INSERT INTO GAME_TBL (GAME_NAME,GAME_GENRE,GAME_MANUFACTURER) VALUES ('Roulette','Casino','ComeOn');
INSERT INTO GAME_TBL (GAME_NAME,GAME_GENRE,GAME_MANUFACTURER) VALUES ('Torchlight','ActionRPG','EA Games');
INSERT INTO GAME_TBL (GAME_NAME,GAME_GENRE,GAME_MANUFACTURER) VALUES ('Diablo III','ActionRPG','Blizzard');

INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (1,1,1);
INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (1,2,1);
INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (1,3,0);
INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (2,3,1);
INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (2,5,1);
INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (3,1,1);
INSERT INTO GAME_LOVE_TBL (PLAYER_ID,GAME_ID,LOVED) VALUES (3,4,1);